server:
  port: 2000
  error:
    include-stacktrace: never

app:
  jwtSecret: 7979B9877
  jwtExpirationMs: 1800000

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:h2:mem:usersDb
    platform: h2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
